#!/usr/bin/env bash

# Function to print subdomain and domain information
print_domain_subdomain() {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F'[[:space:]]+' 'NR==2 { printf "The subdomain %s is a %s record and points to %s\n", $1, $4, $5 }'
}

# Check if exactly two arguments are provided
if [[ $# -eq  2 ]]; then
    print_domain_subdomain "$1.$2" "$2"
else
    # Default subdomains to check if only the domain is provided
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        print_domain_subdomain "${subdomain}.$1" "$subdomain"
    done
fi
