#!/usr/bin/env bash
# upgrade package list and update for install
sudo apt-get update -y
sudo apt-get install -y nginx

#configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen80;/g' /etc/ngix/sites-available/default
sudo service nginx reload
echo "<h1>Hello World</h1>" | sudo tee /var/www/html/index.html
