#!/usr/bin/env bash
#configures a new ubuntu and handles redirect

set -e
echo -e "Updating ang installing Nginx.\n"
sudo apt-get update
sudo apt install nginx -y

echo -e "\nSetting up.\n"
sudo start nginx service
#Allow Nginx on firewall and user ownership 
sudo ufw allow 'nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/htmal/index.html.nginx-de
bian.html.bckp
echo -e "Hello World!" > /var/www/html/index.html.nginx-debian.html
sudo sed -i '24i\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2
-TGU permanent;' /etc/nginx/sites-available/default
sudo restart nginx service
echo -e "finished.\n"
