#!/usr/bin/env bash
#displays Best School 10 times

count=0
while [ $count -le 10 ]; do
    if [ $count -eq 8 ]; then
        echo -n "Best School "
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
