#!/usr/bin/env bash
#configuring nginx to run as the nginx user.
service nginx start
nginx_conf="/etc/nginx/nginx.conf"
server_block=$(cat <<EOF
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
}
EOF
)
sed -i "s/http {/http{\n$ {$server_block}/" "$nginx_conf"
service nginx restart
