#!/usr/bin/env bash
#Edit Nginx configuration file
nginx_conf="/etc/nginx/nginx.conf"

#define the server block
server_block=$(cat <<EOF
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
}
EOF
)
sed -i "s/http {/http{\n$ {$server_block}/" "$nginx_conf"
#Restart Nginx service
service nginx restart
